# Generated by Django 3.2.9 on 2023-05-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default_avatar',
            name='avatar',
            field=models.ImageField(upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(blank=True, default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.zooniverse.org%2Fprojects%2Fpenguintom79%2Fpenguin-watch&psig=AOvVaw3znYM4x-Z6U1aNeuECcWYg&ust=1639545794567000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCPjdrsbG4vQCFQAAAAAdAAAAABAH', null=True, upload_to='profiles/'),
        ),
    ]
