# Generated by Django 3.2.9 on 2021-12-18 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=250, null=True)),
                ('image', models.ImageField(null=True, upload_to='static/images/pictures/category')),
                ('shortly_description', models.CharField(blank=True, max_length=250, null=True)),
                ('shortly_comment', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SubcategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_slug', models.CharField(max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('name', models.CharField(max_length=150, null=True)),
                ('slug', models.CharField(max_length=250, null=True)),
                ('image', models.ImageField(null=True, upload_to='static/images/pictures/subcategory')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categorymodel')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='static/images/pictures/product')),
                ('subcategory_slug', models.CharField(max_length=250, null=True)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
                ('price', models.FloatField(null=True)),
                ('old_price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
                ('color', models.CharField(blank=True, max_length=80, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('guaranty', models.CharField(blank=True, max_length=80, null=True)),
                ('manufacture', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categorymodel')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategorymodel')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Product_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='static/images/pictures/product')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.productmodel')),
            ],
        ),
    ]
