# Generated by Django 3.2.9 on 2023-05-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(null=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='image',
            field=models.ImageField(null=True, upload_to='product/inlines/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='subcategorymodel',
            name='image',
            field=models.ImageField(null=True, upload_to='subcategory/'),
        ),
    ]
